# Generated by Django 3.1 on 2020-08-12 15:29

from django.db import migrations, models
import shortener.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Url",
            fields=[
                ("slug", models.SlugField(primary_key=True, serialize=False)),
                ("full_url", models.URLField(max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_index=True,
                        default=shortener.models.expires_at_default,
                    ),
                ),
                ("clicks", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
